package dev.aiengg.potholereporter.plugin

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.media.MediaMetadataRetriever
import android.net.Uri
import android.os.Build
import android.util.Base64
import androidx.room.withTransaction
import androidx.core.content.ContextCompat
import androidx.core.content.FileProvider
import dev.aiengg.potholereporter.MainActivity
import dev.aiengg.potholereporter.db.FootageSegmentEntity
import dev.aiengg.potholereporter.db.PotholeDatabase
import dev.aiengg.potholereporter.db.RepairTargetEntity
import dev.aiengg.potholereporter.db.SessionEntity
import dev.aiengg.potholereporter.drive.DriveEndSummary
import dev.aiengg.potholereporter.drive.DriveForegroundService
import dev.aiengg.potholereporter.drive.DriveSessionLimitPolicy
import dev.aiengg.potholereporter.drive.NotificationHelper
import com.getcapacitor.JSArray
import com.getcapacitor.JSObject
import com.getcapacitor.Plugin
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin
import com.getcapacitor.annotation.Permission
import com.getcapacitor.annotation.PermissionCallback
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.File
import java.util.UUID

internal object FootagePathPolicy {
    // Drive IDs are directory names generated by the app. Keep them to one portable,
    // unambiguous path component; dots and separators have no valid use here.
    private val safeSessionId = Regex("[A-Za-z0-9][A-Za-z0-9_-]{0,127}")

    fun sessionDirectory(filesDir: File, sessionId: String): File {
        require(safeSessionId.matches(sessionId)) { "Invalid drive session" }
        val footageRoot = File(filesDir, "footage").canonicalFile
        val target = File(footageRoot, sessionId).canonicalFile
        require(target != footageRoot && target.parentFile == footageRoot) {
            "Invalid drive session"
        }
        return target
    }

    fun segmentFile(sessionDirectory: File, storedPath: String): File {
        val canonicalSession = sessionDirectory.canonicalFile
        val target = File(storedPath).canonicalFile
        require(target != canonicalSession && target.parentFile == canonicalSession) {
            "Stored footage path is outside this drive"
        }
        return target
    }

    fun keyframeFile(sessionDirectory: File, storedPath: String): File {
        val canonicalSession = sessionDirectory.canonicalFile
        val keyframeDirectory = File(canonicalSession, "keyframes").canonicalFile
        require(keyframeDirectory.parentFile == canonicalSession) { "Invalid keyframe directory" }
        val target = File(storedPath).canonicalFile
        require(target != keyframeDirectory && target.parentFile == keyframeDirectory) {
            "Stored keyframe path is outside this drive"
        }
        return target
    }
}

internal class PendingStartGate<T> {
    private var settled = false
    private var cancellationRequested = false
    private var startRequestAccepted = false
    private var stopIntentQueued = false
    private val stopWaiters = mutableListOf<T>()

    @Synchronized
    fun requestCancellation(stopWaiter: T? = null): Boolean {
        if (settled) return false
        cancellationRequested = true
        if (stopWaiter != null) stopWaiters.add(stopWaiter)
        return true
    }

    @Synchronized
    fun isCancellationRequested(): Boolean = cancellationRequested

    @Synchronized
    fun hasStopWaiters(): Boolean = stopWaiters.isNotEmpty()

    @Synchronized
    fun anyWaiter(predicate: (T) -> Boolean): Boolean = stopWaiters.any(predicate)

    @Synchronized
    fun claimReady(): Boolean {
        if (settled || cancellationRequested) return false
        settled = true
        return true
    }

    @Synchronized
    fun markStartRequestAccepted(): Boolean {
        startRequestAccepted = true
        return cancellationRequested
    }

    @Synchronized
    fun queueStopIntentOnce(): Boolean {
        if (!startRequestAccepted || stopIntentQueued) return false
        stopIntentQueued = true
        return true
    }

    @Synchronized
    fun settleCancellation(): List<T> {
        if (settled) return emptyList()
        settled = true
        return stopWaiters.toList().also { stopWaiters.clear() }
    }
}

@CapacitorPlugin(
    name = "DriveMode",
    permissions = [
        Permission(strings = [Manifest.permission.CAMERA], alias = "camera"),
        Permission(
            strings = [Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION],
            alias = "location"
        ),
        Permission(strings = [Manifest.permission.POST_NOTIFICATIONS], alias = "notifications")
    ]
)
class DriveModePlugin : Plugin() {

    private val pluginScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val pendingStartLock = Any()
    private var pendingStart: PendingDriveStart? = null
    @Volatile private var nativeStateReconciled = false
    private val nativeStateReconcileMutex = Mutex()

    private data class PendingDriveStart(
        val call: PluginCall,
        val requestId: String = UUID.randomUUID().toString(),
        val gate: PendingStartGate<PendingCancellationWaiter> = PendingStartGate()
    )

    private data class PendingCancellationWaiter(
        val discardData: Boolean,
        val onStopped: (DriveEndSummary?) -> Unit,
        val onFailure: () -> Unit
    )

    private companion object {
        const val START_READY_TIMEOUT_MS = 12_000L
        const val START_CANCEL_TIMEOUT_MS = 25_000L
        const val START_POLL_MS = 50L
        const val MAX_REPAIR_TARGETS = 2_000
        const val MAX_REPAIR_TARGET_IMAGE_BYTES = 4 * 1024 * 1024
        const val MAX_KEYFRAME_IMAGE_BYTES = 8 * 1024 * 1024
    }

    override fun load() {
        super.load()
        DriveForegroundService.onStatusListener = { status ->
            val data = JSObject().apply {
                put("isRunning", status.isRunning)
                put("isPaused", status.isPaused)
                put("isPausing", status.isPausing)
                put("isStopping", status.isStopping)
                put("sessionId", status.sessionId)
                put("checked", status.checked)
                put("found", status.found)
                put("already", status.already)
                put("queued", status.queued)
                put("dropped", status.dropped)
                put("status", status.status)
                put("recordingEnabled", status.recordingEnabled)
                put("isRecording", status.isRecording)
                put("videoSupported", status.videoSupported)
                put("segmentCount", status.segmentCount)
                put("recordedBytes", status.recordedBytes)
                put("cameraActive", status.cameraActive)
                put("recordingIssue", status.recordingIssue)
                put("keyframeCount", status.keyframeCount)
                put("remainingMs", status.remainingMs)
                put("maxDurationMinutes", status.maxDurationMinutes)
            }
            notifyListeners("driveStatusChange", data)
        }

        DriveForegroundService.onReportListener = { reportId, damageType, address ->
            val data = JSObject().apply {
                put("reportId", reportId)
                put("damageType", damageType)
                put("address", address)
            }
            notifyListeners("reportFound", data)
        }

        DriveForegroundService.onDriveEndedListener = { summary ->
            notifyListeners("driveEnded", endSummaryObject(summary))
        }
    }

    @PluginMethod
    fun startDrive(call: PluginCall) {
        val apiKey = call.getString("apiKey") ?: ""
        val model = call.getString("model") ?: "gpt-5-mini"
        val detail = call.getString("detail") ?: "high"
        val language = call.getString("language") ?: "en"
        val debug = call.getBoolean("debug") ?: false
        val recordVideo = call.getBoolean("recordVideo") ?: false
        val maxDurationMinutes = (call.getInt("maxDurationMinutes")
            ?: DriveSessionLimitPolicy.DEFAULT_LIMIT_MINUTES).coerceIn(
            DriveSessionLimitPolicy.MIN_LIMIT_MINUTES,
            DriveSessionLimitPolicy.MAX_LIMIT_MINUTES
        )

        if (!hasDrivePermissions()) {
            call.reject("Camera and location permission are required before Drive Mode can start")
            return
        }
        if (!hasNotificationPermission()) {
            call.reject("Enable Pothole Reporter notifications in Android Settings so camera use is always visible")
            return
        }
        if (apiKey.isBlank()) {
            call.reject("An OpenAI API key is required")
            return
        }
        val existing = DriveForegroundService.status()
        if (existing.isRunning) {
            // This call did not create that session. During a phone/video-call camera
            // interruption it is legitimately running with cameraActive=false; return
            // the truthful status without timing out or stopping somebody else's drive.
            call.resolve(statusObject(existing))
            return
        }
        if (existing.isStopping) {
            call.reject("The previous drive is still stopping safely")
            return
        }
        val pending = PendingDriveStart(call)
        val accepted = synchronized(pendingStartLock) {
            if (pendingStart != null) false else {
                pendingStart = pending
                true
            }
        }
        if (!accepted) {
            call.reject("Drive Mode is already starting")
            return
        }
        val context = context
        val serviceIntent = Intent(context, DriveForegroundService::class.java).apply {
            action = DriveForegroundService.ACTION_START
            putExtra(DriveForegroundService.EXTRA_API_KEY, apiKey)
            putExtra(DriveForegroundService.EXTRA_MODEL, model)
            putExtra(DriveForegroundService.EXTRA_DETAIL, detail)
            putExtra(DriveForegroundService.EXTRA_LANGUAGE, language)
            putExtra(DriveForegroundService.EXTRA_DEBUG, debug)
            putExtra(DriveForegroundService.EXTRA_RECORD_VIDEO, recordVideo)
            putExtra(DriveForegroundService.EXTRA_MAX_DRIVE_MINUTES, maxDurationMinutes)
            putExtra(DriveForegroundService.EXTRA_START_REQUEST_ID, pending.requestId)
        }

        try {
            ContextCompat.startForegroundService(context, serviceIntent)
        } catch (error: Exception) {
            synchronized(pendingStartLock) {
                if (pendingStart === pending) pendingStart = null
            }
            val waiters = pending.gate.settleCancellation()
            call.reject("Drive Mode could not start: ${error.message ?: "service start failed"}")
            waiters.forEach { it.onStopped(null) }
            return
        }
        if (pending.gate.markStartRequestAccepted()) queuePendingStartStop(pending)
        monitorPendingStart(pending)
    }

    @PluginMethod
    fun pauseDrive(call: PluginCall) {
        val service = DriveForegroundService.activeService
        if (service == null) call.resolve(statusObject(DriveForegroundService.status()))
        else service.pauseDrive { call.resolve(statusObject(it)) }
    }

    @PluginMethod
    fun resumeDrive(call: PluginCall) {
        val service = DriveForegroundService.activeService
        if (service == null) call.resolve(statusObject(DriveForegroundService.status()))
        else service.resumeDrive { call.resolve(statusObject(it)) }
    }

    @PluginMethod
    fun stopDrive(call: PluginCall) {
        val waiter = PendingCancellationWaiter(
            discardData = false,
            onStopped = { summary ->
                call.resolve(summary?.let(::endSummaryObject) ?: JSObject().apply {
                    put("stopped", true)
                    put("discarded", true)
                    put("cancelledStart", true)
                })
            },
            onFailure = { call.reject("Drive start could not be cancelled safely") }
        )
        val pending = synchronized(pendingStartLock) {
            pendingStart?.takeIf { it.gate.requestCancellation(waiter) }
        }
        if (pending != null) {
            queuePendingStartStop(pending)
            return
        }
        val service = DriveForegroundService.activeService
        if (service != null) {
            service.stopDriveSession { summary -> call.resolve(endSummaryObject(summary)) }
        } else {
            call.resolve(JSObject().apply { put("stopped", false) })
        }
    }

    private fun monitorPendingStart(pending: PendingDriveStart) {
        pluginScope.launch {
            val readyDeadline = System.currentTimeMillis() + START_READY_TIMEOUT_MS
            var failure: String? = null
            while (System.currentTimeMillis() < readyDeadline) {
                if (pending.gate.isCancellationRequested()) {
                    failure = "Drive start was cancelled"
                    break
                }
                val completedStart = DriveForegroundService.completedStartSummary(pending.requestId)
                if (completedStart != null) {
                    pending.gate.requestCancellation()
                    failure = completedStart.error ?: "Drive camera failed to start"
                    break
                }
                val status = DriveForegroundService.status()
                if (status.isStopping) {
                    pending.gate.requestCancellation()
                    failure = status.recordingIssue
                        ?: status.status.takeUnless { it.isBlank() || it == "Stopping safely" }
                        ?: "Drive camera failed to start"
                    break
                }
                // Pause is a valid, user-visible terminal state for startup. It turns
                // the camera off deliberately and must not become a 12-second failure.
                if (DriveForegroundService.activeStartRequestId() == pending.requestId &&
                    status.isRunning && (status.cameraActive || status.isPaused)) {
                    if (pending.gate.claimReady()) {
                        synchronized(pendingStartLock) {
                            if (pendingStart === pending) pendingStart = null
                        }
                        pending.call.resolve(statusObject(status))
                        return@launch
                    }
                    failure = "Drive start was cancelled"
                    break
                }
                delay(START_POLL_MS)
            }

            if (failure == null) {
                pending.gate.requestCancellation()
                failure = "Drive camera did not become ready within ${START_READY_TIMEOUT_MS / 1000} seconds"
            }
            // A user Stop queues ACTION_STOP at request time. Timeout/camera-failure
            // cleanup does not enqueue a fresh FGS start; it stops the active/pending
            // component directly and waits for the service's durable Stop callback.
            if (pending.gate.hasStopWaiters()) queuePendingStartStop(pending)
            val discardData = pending.gate.anyWaiter { it.discardData }
            val cancellation = awaitPendingStartCancellation(pending, discardData)
            val waiters = pending.gate.settleCancellation()
            val finalSummary = cancellation.summary?.let { summary ->
                if (waiters.any { it.discardData }) summary.copy(discarded = true) else summary
            }
            synchronized(pendingStartLock) {
                if (pendingStart === pending) pendingStart = null
            }
            pending.call.reject(failure ?: "Drive camera failed to start")
            waiters.forEach { waiter ->
                if (cancellation.stopped) waiter.onStopped(finalSummary)
                else waiter.onFailure()
            }
        }
    }

    private fun queuePendingStartStop(pending: PendingDriveStart) {
        if (!pending.gate.queueStopIntentOnce()) return
        // This request is queued only after ACTION_START was accepted, while the user
        // is still in the foreground. Android delivers the two starts in order, so a
        // delayed ACTION_START cannot survive as a hidden camera session.
        runCatching {
            context.startService(Intent(context, DriveForegroundService::class.java).apply {
                action = DriveForegroundService.ACTION_STOP
                putExtra(DriveForegroundService.EXTRA_STOP_REQUEST_ID, pending.requestId)
                putExtra(
                    DriveForegroundService.EXTRA_STOP_DISCARD_DATA,
                    pending.gate.anyWaiter { it.discardData }
                )
            })
        }
    }

    private data class PendingCancellationResult(
        val stopped: Boolean,
        val summary: DriveEndSummary?
    )

    private suspend fun awaitPendingStartCancellation(
        pending: PendingDriveStart,
        discardData: Boolean
    ): PendingCancellationResult {
        val completion = CompletableDeferred<DriveEndSummary>()
        var callbackRegistered = false
        var lastStatus = DriveForegroundService.status()
        val deadline = System.currentTimeMillis() + START_CANCEL_TIMEOUT_MS
        while (System.currentTimeMillis() < deadline) {
            DriveForegroundService.completedStartSummary(pending.requestId)?.let {
                return PendingCancellationResult(true, it)
            }
            val service = DriveForegroundService.activeService
            lastStatus = DriveForegroundService.status()
            val activeRequest = DriveForegroundService.activeStartRequestId()
            if (!callbackRegistered && activeRequest == pending.requestId && service != null &&
                (lastStatus.isRunning || lastStatus.isStopping)) {
                callbackRegistered = true
                withContext(Dispatchers.Main) {
                    service.stopDriveSession(
                        reason = "Drive start cancelled",
                        discardData = discardData
                    ) { summary -> completion.complete(summary) }
                }
            }
            if (completion.isCompleted) {
                return PendingCancellationResult(true, completion.await())
            }
            if (callbackRegistered && DriveForegroundService.activeService == null) {
                return PendingCancellationResult(true, cancellationSummary(lastStatus, discardData))
            }
            delay(START_POLL_MS)
        }

        // The service never acknowledged the queued cancellation. Force-stop this
        // component, then verify the in-process service reference is gone before any
        // pending Stop call is allowed to resolve.
        withContext(Dispatchers.Main) {
            if (DriveForegroundService.activeStartRequestId() in arrayOf(null, pending.requestId)) {
                context.stopService(Intent(context, DriveForegroundService::class.java))
            }
        }
        val forceDeadline = System.currentTimeMillis() + 2_000L
        while (System.currentTimeMillis() < forceDeadline &&
            DriveForegroundService.activeService != null) {
            delay(START_POLL_MS)
        }
        return PendingCancellationResult(
            stopped = DriveForegroundService.completedStartSummary(pending.requestId) != null ||
                DriveForegroundService.activeStartRequestId() != pending.requestId,
            summary = completion.takeIf { it.isCompleted }?.await()
                ?: DriveForegroundService.completedStartSummary(pending.requestId)
                ?: cancellationSummary(lastStatus, discardData)
        )
    }

    private fun cancellationSummary(
        status: dev.aiengg.potholereporter.drive.DriveStatusSnapshot,
        discardData: Boolean
    ) =
        DriveEndSummary(
            sessionId = status.sessionId.orEmpty(),
            checked = status.checked,
            found = status.found,
            already = status.already,
            discarded = discardData,
            reason = status.status
        )

    @PluginMethod
    fun getStatus(call: PluginCall) {
        call.resolve(statusObject(DriveForegroundService.status()))
    }

    @PluginMethod
    fun attachPreview(call: PluginCall) {
        val left = call.getDouble("left") ?: 0.0
        val top = call.getDouble("top") ?: 0.0
        val width = call.getDouble("width") ?: 0.0
        val height = call.getDouble("height") ?: 0.0
        val viewportWidth = call.getDouble("viewportWidth") ?: 0.0
        val viewportHeight = call.getDouble("viewportHeight") ?: 0.0
        if (width <= 0 || height <= 0 || viewportWidth <= 0 || viewportHeight <= 0) {
            call.reject("Preview bounds are invalid")
            return
        }
        if (DriveForegroundService.activeService == null || !DriveForegroundService.status().isRunning) {
            call.reject("Drive camera is still starting")
            return
        }
        (activity as? MainActivity)?.showDrivePreview(left, top, width, height, viewportWidth, viewportHeight)
        call.resolve()
    }

    @PluginMethod
    fun detachPreview(call: PluginCall) {
        (activity as? MainActivity)?.hideDrivePreview()
        call.resolve()
    }

    @PluginMethod
    fun setVideoRecording(call: PluginCall) {
        val enabled = call.getBoolean("enabled") ?: false
        val service = DriveForegroundService.activeService
        if (service == null || !DriveForegroundService.status().isRunning) {
            call.reject("Drive Mode is not running")
            return
        }
        service.setVideoRecordingEnabled(enabled) { call.resolve(statusObject(it)) }
    }

    @PluginMethod
    fun requestDrivePermissions(call: PluginCall) {
        val aliases = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            arrayOf("camera", "location", "notifications")
        } else arrayOf("camera", "location")
        requestPermissionForAliases(aliases, call, "drivePermissionsResult")
    }

    @PermissionCallback
    private fun drivePermissionsResult(call: PluginCall) {
        val ret = JSObject().apply {
            put("granted", hasDrivePermissions())
            put("notificationsGranted", Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU ||
                ContextCompat.checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS) == PackageManager.PERMISSION_GRANTED)
        }
        call.resolve(ret)
    }

    @PluginMethod
    fun syncReports(call: PluginCall) {
        val limit = (call.getInt("limit") ?: 5).coerceIn(1, 5)
        pluginScope.launch {
            try {
                val db = PotholeDatabase.getDatabase(context)
                // Evidence images cross the Capacitor bridge as Base64. Bound each page so
                // a long drive cannot allocate the entire outbox in Java and JS at once.
                val unsynced = db.reportDao().getUnsyncedReports(limit)
                val array = JSArray()
                for (r in unsynced) {
                    val obj = JSObject().apply {
                        put("id", r.id)
                        put("created_at", r.createdAt)
                        put("lat", r.lat)
                        put("lng", r.lng)
                        put("address", r.address)
                        put("photo_data_url", r.photoDataUrl)
                        put("photo_path", r.photoPath)
                        put("photo_full_data_url", fileAsDataUrl(r.photoFullPath ?: r.photoPath))
                        put("is_reportable", r.isReportable)
                        put("is_pothole", r.isPothole)
                        put("damage_type", r.damageType)
                        put("assessment", r.assessment)
                        put("image_quality", r.imageQuality)
                        put("on_drivable_surface", r.onDrivableSurface)
                        put("has_broken_edge_or_rim", r.hasBrokenEdgeOrRim)
                        put("has_depth_or_surface_loss", r.hasDepthOrSurfaceLoss)
                        put("temporal_consistency", r.temporalConsistency)
                        put("size", r.size)
                        put("decision", r.decision)
                        put("description", r.description)
                        put("email_subject", r.emailSubject)
                        put("email_body", r.emailBody)
                        put("status", r.status)
                        put("detection_model", r.detectionModel)
                        put("image_detail", r.imageDetail)
                        put("prompt_version", r.promptVersion)
                        put("schema_version", r.schemaVersion)
                        put("evidence_count", r.evidenceCount)
                        put("drive_id", r.driveId)
                        put("capture_source", r.captureSource)
                        put("source_event_key", r.sourceEventKey)
                        put("captured_at", r.capturedAt)
                        put("source_offset_s", r.sourceOffsetS)
                        put("gps_accuracy", r.gpsAccuracy)
                        put("speed_mps", r.speedMps)
                        put("heading", r.heading)
                        put("seen_count", r.seenCount)
                        put("last_seen_at", r.lastSeenAt)
                        put("primary_frame_index", r.primaryFrameIndex)
                        put("debug_capture", r.debugCapture)
                    }
                    array.put(obj)
                }

                val ret = JSObject().apply {
                    put("reports", array)
                    put("count", array.length())
                    put("remaining", db.reportDao().countUnsyncedReports())
                }
                call.resolve(ret)
            } catch (e: Exception) {
                call.reject("Failed to sync reports: ${e.message}")
            }
        }
    }

    @PluginMethod
    fun acknowledgeReports(call: PluginCall) {
        val idsArray = call.getArray("ids") ?: JSArray()
        val ids = mutableListOf<Long>()
        for (index in 0 until idsArray.length()) {
            val value = idsArray.optLong(index, -1L)
            if (value > 0) ids.add(value)
        }
        pluginScope.launch {
            try {
                if (ids.isNotEmpty()) PotholeDatabase.getDatabase(context).reportDao().markReportsSynced(ids)
                call.resolve(JSObject().apply { put("acknowledged", ids.size) })
            } catch (error: Exception) {
                call.reject("Failed to acknowledge reports: ${error.message}")
            }
        }
    }

    /**
     * Atomically replaces the WebView-to-native repair cache. A generation directory
     * means a malformed or interrupted payload cannot leave Room pointing at a
     * half-written set of historical evidence images.
     */
    @PluginMethod
    fun replaceRepairTargets(call: PluginCall) {
        val targetsArray = call.getArray("targets")
        if (targetsArray == null) {
            call.reject("Repair targets are required")
            return
        }
        if (targetsArray.length() > MAX_REPAIR_TARGETS) {
            call.reject("Too many repair targets")
            return
        }
        pluginScope.launch {
            val root = File(context.filesDir, "repair_targets")
            val generation = File(root, "generation-${UUID.randomUUID()}")
            try {
                if (!generation.mkdirs()) throw IllegalStateException("could not create repair target storage")
                val parsed = mutableListOf<RepairTargetEntity>()
                val seenIds = HashSet<Long>()
                for (index in 0 until targetsArray.length()) {
                    val obj = targetsArray.getJSONObject(index)
                    val id = obj.optLong("id", -1L)
                    if (id <= 0 || !seenIds.add(id)) {
                        throw IllegalArgumentException("repair target id is invalid or duplicated")
                    }
                    val lat = obj.optDouble("lat", Double.NaN)
                    val lng = obj.optDouble("lng", Double.NaN)
                    if (!lat.isFinite() || !lng.isFinite() || kotlin.math.abs(lat) > 90 ||
                        kotlin.math.abs(lng) > 180) {
                        throw IllegalArgumentException("repair target location is invalid")
                    }
                    val gpsAccuracy = nullableFiniteFloat(obj, "gps_accuracy")?.also {
                        if (it < 0f) throw IllegalArgumentException("repair target GPS accuracy is invalid")
                    }
                    val heading = nullableFiniteFloat(obj, "heading")?.let {
                        (it % 360f + 360f) % 360f
                    }
                    val captureSource = obj.optString("capture_source", "").take(40)
                    val damageType = obj.optString("damage_type", "")
                    if (damageType !in setOf("pothole_cavity", "failed_patch", "surface_breakup",
                            "rut_or_depression", "other_road_damage")) {
                        throw IllegalArgumentException("repair target damage type is invalid")
                    }
                    val condition = obj.optString("condition_status", "open")
                    if (condition !in setOf("open", "repair_review", "fixed")) {
                        throw IllegalArgumentException("repair target condition is invalid")
                    }
                    val lastDamageObservedRaw = obj.optDouble(
                        "last_damage_observed_at", Double.NaN
                    )
                    if (!lastDamageObservedRaw.isFinite() || lastDamageObservedRaw <= 0.0 ||
                        lastDamageObservedRaw > Long.MAX_VALUE.toDouble()) {
                        throw IllegalArgumentException(
                            "repair target last damage observation is invalid"
                        )
                    }
                    val lastDamageObservedAt = kotlin.math.floor(lastDamageObservedRaw).toLong()
                    val decoded = decodeImageDataUrl(obj.optString("photo_data_url", ""))
                    val extension = when (decoded.first) {
                        "image/png" -> "png"
                        "image/webp" -> "webp"
                        "image/gif" -> "gif"
                        else -> "jpg"
                    }
                    val evidence = File(generation, "target-$id.$extension")
                    evidence.outputStream().use { it.write(decoded.second) }
                    parsed.add(RepairTargetEntity(
                        reportId = id,
                        lat = lat,
                        lng = lng,
                        gpsAccuracy = gpsAccuracy,
                        heading = heading,
                        captureSource = captureSource,
                        photoPath = evidence.absolutePath,
                        photoMime = decoded.first,
                        damageType = damageType,
                        conditionStatus = condition,
                        lastDamageObservedAt = lastDamageObservedAt
                    ))
                }

                val db = PotholeDatabase.getDatabase(context)
                var effectiveTargets = parsed.toList()
                db.withTransaction {
                    // An unacknowledged native observation is newer than the WebView
                    // snapshot by definition. Preserve it if replacement runs before
                    // IndexedDB has durably applied and acknowledged the outbox row.
                    val pendingByTarget = db.repairObservationDao()
                        .getUnsyncedObservations()
                        .associateBy { it.targetReportId }
                    effectiveTargets = parsed.map { target ->
                        val pending = pendingByTarget[target.reportId]
                        if (pending != null && pending.observedAt > target.lastDamageObservedAt &&
                            pending.currentCondition in setOf("fixed", "repair_review")) {
                            target.copy(
                                conditionStatus = pending.currentCondition,
                                lastObservedDriveId = pending.driveId,
                                lastObservedAt = pending.observedAt
                            )
                        } else target
                    }
                    db.repairTargetDao().clearAll()
                    if (effectiveTargets.isNotEmpty()) {
                        db.repairTargetDao().insertTargets(effectiveTargets)
                    }
                }
                // Room replacement is atomic. If Drive is active, retain the prior
                // generation until the next idle refresh because an inference already
                // in flight may still hold one of its photo paths.
                val currentStatus = DriveForegroundService.status()
                if (!currentStatus.isRunning && !currentStatus.isStopping) {
                    root.listFiles()?.filter { it != generation }?.forEach { it.deleteRecursively() }
                }
                call.resolve(JSObject().apply { put("replaced", effectiveTargets.size) })
            } catch (error: Exception) {
                generation.deleteRecursively()
                call.reject("Failed to replace repair targets: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun syncRepairObservations(call: PluginCall) {
        pluginScope.launch {
            try {
                val observations = PotholeDatabase.getDatabase(context)
                    .repairObservationDao().getUnsyncedObservations()
                val array = JSArray()
                observations.forEach { observation ->
                    array.put(JSObject().apply {
                        put("id", observation.id)
                        put("target_report_id", observation.targetReportId)
                        put("source_event_key", observation.sourceEventKey)
                        put("observed_at", observation.observedAt)
                        put("drive_id", observation.driveId)
                        put("lat", observation.lat)
                        put("lng", observation.lng)
                        put("gps_accuracy", observation.gpsAccuracy)
                        put("speed_mps", observation.speedMps)
                        put("heading", observation.heading)
                        put("current_photo_data_url", fileAsDataUrl(observation.currentPhotoPath))
                        // Room records the resulting local status (fixed/review). The
                        // WebView independently derives that status from the raw semantic
                        // claim and assessment, so never ask it to trust a native label.
                        put("current_condition", if (observation.currentCondition in
                            setOf("fixed", "repair_review")) "repaired"
                            else observation.currentCondition)
                        put("assessment", observation.assessment)
                        put("image_quality", observation.imageQuality)
                        put("same_location_visible", observation.sameLocationVisible)
                        put("completed_repair_visible", observation.completedRepairVisible)
                        put("description", observation.description)
                        put("detection_model", observation.detectionModel)
                        put("image_detail", observation.imageDetail)
                        put("prompt_version", observation.promptVersion)
                        put("schema_version", observation.schemaVersion)
                    })
                }
                call.resolve(JSObject().apply {
                    put("observations", array)
                    put("count", array.length())
                })
            } catch (error: Exception) {
                call.reject("Failed to sync repair observations: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun acknowledgeRepairObservations(call: PluginCall) {
        val idsArray = call.getArray("ids") ?: JSArray()
        val ids = mutableListOf<Long>()
        for (index in 0 until idsArray.length()) {
            val value = idsArray.optLong(index, -1L)
            if (value > 0) ids.add(value)
        }
        pluginScope.launch {
            try {
                if (ids.isNotEmpty()) {
                    val distinctIds = ids.distinct()
                    val dao = PotholeDatabase.getDatabase(context).repairObservationDao()
                    val acknowledged = dao.getObservations(distinctIds)
                    // IndexedDB has its own Blob now. Remove the durable outbox rows,
                    // then best-effort remove their native copies so revisits do not
                    // accumulate hidden JPEGs forever.
                    dao.deleteObservations(distinctIds)
                    acknowledged.forEach { runCatching { File(it.currentPhotoPath).delete() } }
                }
                call.resolve(JSObject().apply { put("acknowledged", ids.distinct().size) })
            } catch (error: Exception) {
                call.reject("Failed to acknowledge repair observations: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun openMaps(call: PluginCall) {
        val navigation = Intent(Intent.ACTION_VIEW, Uri.parse("geo:0,0?q="))
        navigation.setPackage("com.google.android.apps.maps")
        val chosen = if (navigation.resolveActivity(context.packageManager) != null) navigation
            else Intent(Intent.ACTION_VIEW, Uri.parse("geo:0,0?q="))
        chosen.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chosen)
        call.resolve()
    }

    @PluginMethod
    fun clearNativeData(call: PluginCall) {
        val clearData = {
          pluginScope.launch {
            try {
                val db = PotholeDatabase.getDatabase(context)
                val reportsRoot = File(context.filesDir, "reports")
                val footageRoot = File(context.filesDir, "footage")
                val repairTargetsRoot = File(context.filesDir, "repair_targets")
                if (reportsRoot.exists() && (!reportsRoot.deleteRecursively() || reportsRoot.exists())) {
                    throw IllegalStateException("some report photos could not be deleted")
                }
                if (footageRoot.exists() && (!footageRoot.deleteRecursively() || footageRoot.exists())) {
                    throw IllegalStateException("some recorded footage could not be deleted")
                }
                if (repairTargetsRoot.exists() &&
                    (!repairTargetsRoot.deleteRecursively() || repairTargetsRoot.exists())) {
                    throw IllegalStateException("some repair target photos could not be deleted")
                }
                db.footageDao().clearAll()
                db.driveKeyframeDao().clearAll()
                db.eventSightingDao().clearAll()
                db.repairObservationDao().clearAll()
                db.repairTargetDao().clearAll()
                db.reportDao().clearAll()
                db.sessionDao().clearAll()
                call.resolve()
            } catch (error: Exception) {
                call.reject("Failed to clear native data: ${error.message}")
              }
          }
        }
        val pendingWaiter = PendingCancellationWaiter(
            discardData = true,
            onStopped = { clearData(); Unit },
            onFailure = { call.reject("Failed to clear native data: Drive start could not be cancelled safely") }
        )
        val pending = synchronized(pendingStartLock) {
            pendingStart?.takeIf { it.gate.requestCancellation(pendingWaiter) }
        }
        if (pending != null) {
            queuePendingStartStop(pending)
            return
        }
        val service = DriveForegroundService.activeService
        if (service == null) clearData()
        else service.stopDriveSession("Data cleared", discardData = true) { clearData() }
    }

    @PluginMethod
    fun getDrives(call: PluginCall) {
        pluginScope.launch {
            try {
                val db = PotholeDatabase.getDatabase(context)
                reconcileNativeStateOnce(db)
                val sessions = db.sessionDao().getAllSessions()
                val footageBySession = db.footageDao().getAllSegments().groupBy { it.sessionId }
                val keyframesBySession = db.driveKeyframeDao().getAll().groupBy { it.sessionId }
                val array = JSArray()
                for (s in sessions) {
                    val footage = footageBySession[s.id].orEmpty()
                    val keyframes = keyframesBySession[s.id].orEmpty()
                    val obj = JSObject().apply {
                        put("id", s.id)
                        put("started_at", s.startedAt)
                        put("ended_at", s.endedAt)
                        put("checked", s.checkedCount)
                        put("found", s.foundCount)
                        put("already", s.alreadyCount)
                        put("already_ids", parseJsonArray(s.alreadyIdsJson))
                        put("gps_track", parseGpsTrack(s.gpsTrackJson))
                        put("status", s.status)
                        put("footage_segments", footage.size)
                        put("footage_bytes", footage.sumOf { it.bytes })
                        put("footage_duration_ms", footage.sumOf { it.durationMs })
                        put("keyframe_count", keyframes.size)
                        put("pending_keyframes", keyframes.count { !it.liveAnalyzed })
                        put("keyframe_bytes", keyframes.sumOf { it.bytes })
                    }
                    array.put(obj)
                }
                call.resolve(JSObject().apply { put("drives", array) })
            } catch (e: Exception) {
                call.reject("Failed to get drives: ${e.message}")
            }
        }
    }

    @PluginMethod
    fun listFootage(call: PluginCall) {
        val requestedSession = call.getString("sessionId")
        pluginScope.launch {
            try {
                val dao = PotholeDatabase.getDatabase(context).footageDao()
                val segments = if (requestedSession.isNullOrBlank()) dao.getAllSegments()
                    else dao.getSegmentsForSession(requestedSession)
                val array = JSArray()
                segments.forEach { segment ->
                    array.put(JSObject().apply {
                        put("id", segment.id)
                        put("sessionId", segment.sessionId)
                        put("startedAt", segment.startedAt)
                        put("endedAt", segment.endedAt)
                        put("durationMs", segment.durationMs)
                        put("bytes", segment.bytes)
                        put("complete", segment.complete)
                        put("errorCode", segment.errorCode)
                    })
                }
                call.resolve(JSObject().apply { put("segments", array) })
            } catch (error: Exception) {
                call.reject("Failed to list footage: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun listKeyframes(call: PluginCall) {
        val requestedSession = call.getString("sessionId")
        if (requestedSession.isNullOrBlank()) {
            call.reject("A drive session is required")
            return
        }
        val pendingOnly = call.getBoolean("pendingOnly") ?: true
        pluginScope.launch {
            try {
                requireDriveReplayIsIdle(requestedSession)
                val sessionRoot = FootagePathPolicy.sessionDirectory(context.filesDir, requestedSession)
                val dao = PotholeDatabase.getDatabase(context).driveKeyframeDao()
                val frames = if (pendingOnly) dao.getPendingForSession(requestedSession)
                    else dao.getForSession(requestedSession)
                val array = JSArray()
                frames.forEach { frame ->
                    val file = FootagePathPolicy.keyframeFile(sessionRoot, frame.filePath)
                    if (!file.isFile) return@forEach
                    array.put(JSObject().apply {
                        put("id", frame.id)
                        put("captureSeq", frame.captureSeq)
                        put("capturedAtMs", frame.capturedAtMs)
                        put("sourceOffsetMs", frame.sourceOffsetMs)
                        put("lat", frame.lat)
                        put("lng", frame.lng)
                        put("gpsAccuracy", frame.gpsAccuracy)
                        put("speedMps", frame.speedMps)
                        put("heading", frame.heading)
                        put("width", frame.width)
                        put("height", frame.height)
                        put("bytes", frame.bytes)
                        put("liveAnalyzed", frame.liveAnalyzed)
                    })
                }
                call.resolve(JSObject().apply {
                    put("keyframes", array)
                    put("count", array.length())
                })
            } catch (error: Exception) {
                call.reject("Failed to list saved frames: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun readKeyframe(call: PluginCall) {
        val id = call.getLong("id") ?: -1L
        if (id <= 0L) {
            call.reject("A saved frame is required")
            return
        }
        pluginScope.launch {
            try {
                val db = PotholeDatabase.getDatabase(context)
                val frame = db.driveKeyframeDao().getKeyframe(id)
                    ?: throw IllegalArgumentException("Saved frame not found")
                requireDriveReplayIsIdle(frame.sessionId)
                val sessionRoot = FootagePathPolicy.sessionDirectory(context.filesDir, frame.sessionId)
                val file = FootagePathPolicy.keyframeFile(sessionRoot, frame.filePath)
                if (!file.isFile || file.length() <= 0L || file.length() > MAX_KEYFRAME_IMAGE_BYTES) {
                    throw IllegalStateException("Saved frame is unavailable")
                }
                val temporalContext = nearbyVideoFrameDataUrls(frame.capturedAtMs, frame.sessionId, db)
                val before = temporalContext.filter { it.first < frame.capturedAtMs }
                val after = temporalContext.filter { it.first > frame.capturedAtMs }
                val photos = JSArray().apply {
                    before.forEach { put(it.second) }
                    put("data:image/jpeg;base64," + Base64.encodeToString(file.readBytes(), Base64.NO_WRAP))
                    after.forEach { put(it.second) }
                }
                call.resolve(JSObject().apply {
                    put("id", frame.id)
                    put("sessionId", frame.sessionId)
                    put("captureSeq", frame.captureSeq)
                    put("capturedAtMs", frame.capturedAtMs)
                    put("sourceOffsetMs", frame.sourceOffsetMs)
                    put("lat", frame.lat)
                    put("lng", frame.lng)
                    put("gpsAccuracy", frame.gpsAccuracy)
                    put("speedMps", frame.speedMps)
                    put("heading", frame.heading)
                    put("photos", photos)
                    // Video context is ordered before/evidence/after. The WebView keeps
                    // the evidence frame as the primary image while the model can use
                    // motion/parallax to reject raised speed breakers.
                    put("primaryIndex", before.size)
                })
            } catch (error: Exception) {
                call.reject("Failed to read saved frame: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun markKeyframeAnalyzed(call: PluginCall) {
        val id = call.getLong("id") ?: -1L
        if (id <= 0L) {
            call.reject("A saved frame is required")
            return
        }
        pluginScope.launch {
            try {
                val dao = PotholeDatabase.getDatabase(context).driveKeyframeDao()
                val frame = dao.getKeyframe(id)
                    ?: throw IllegalArgumentException("Saved frame not found")
                requireDriveReplayIsIdle(frame.sessionId)
                dao.markAnalyzed(id)
                call.resolve(JSObject().apply { put("analyzed", id) })
            } catch (error: Exception) {
                call.reject("Failed to checkpoint saved frame: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun shareFootage(call: PluginCall) {
        val requestedSession = call.getString("sessionId")
        if (requestedSession.isNullOrBlank()) {
            call.reject("A drive session is required")
            return
        }
        pluginScope.launch {
            try {
                val segments = PotholeDatabase.getDatabase(context).footageDao()
                    .getSegmentsForSession(requestedSession)
                    .map { File(it.filePath) }
                    .filter(File::isFile)
                if (segments.isEmpty()) {
                    call.reject("No saved video exists for this drive")
                    return@launch
                }
                val uris = ArrayList(segments.map { file ->
                    FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
                })
                val share = Intent(Intent.ACTION_SEND_MULTIPLE).apply {
                    type = "video/mp4"
                    putParcelableArrayListExtra(Intent.EXTRA_STREAM, uris)
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                }
                activity.runOnUiThread {
                    activity.startActivity(Intent.createChooser(share, "Share drive footage"))
                    call.resolve(JSObject().apply { put("shared", uris.size) })
                }
            } catch (error: Exception) {
                call.reject("Failed to share footage: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun deleteFootage(call: PluginCall) {
        val requestedSession = call.getString("sessionId")
        if (requestedSession.isNullOrBlank()) {
            call.reject("A drive session is required")
            return
        }
        try {
            // Reject traversal before querying state or scheduling any filesystem work.
            FootagePathPolicy.sessionDirectory(context.filesDir, requestedSession)
        } catch (_: Exception) {
            call.reject("Invalid drive session")
            return
        }
        val status = DriveForegroundService.status()
        if ((status.isRunning || status.isStopping) && status.sessionId == requestedSession) {
            call.reject("Stop this drive before deleting its footage")
            return
        }
        pluginScope.launch {
            try {
                val dao = PotholeDatabase.getDatabase(context).footageDao()
                val segments = dao.getSegmentsForSession(requestedSession)
                // Resolve and validate every target first. A corrupt database row must
                // not cause a partial deletion before an out-of-scope path is noticed.
                val sessionRoot = FootagePathPolicy.sessionDirectory(context.filesDir, requestedSession)
                val segmentFiles = segments.map {
                    FootagePathPolicy.segmentFile(sessionRoot, it.filePath)
                }
                var deleted = 0
                val failed = segmentFiles.filter { file ->
                    if (!file.exists()) false else if (file.delete()) { deleted++; false } else true
                }
                if (failed.isNotEmpty()) {
                    throw IllegalStateException("${failed.size} video clip(s) could not be deleted")
                }
                if (sessionRoot.exists() && (!sessionRoot.deleteRecursively() || sessionRoot.exists())) {
                    throw IllegalStateException("the footage folder could not be deleted")
                }
                dao.deleteForSession(requestedSession)
                PotholeDatabase.getDatabase(context).driveKeyframeDao()
                    .deleteForSession(requestedSession)
                call.resolve(JSObject().apply { put("deleted", deleted) })
            } catch (error: Exception) {
                call.reject("Failed to delete footage: ${error.message}")
            }
        }
    }

    private fun parseJsonArray(json: String): JSArray {
        val arr = JSArray()
        try {
            val parsed = JSONArray(json)
            for (i in 0 until parsed.length()) {
                arr.put(parsed.get(i))
            }
        } catch (_: Exception) {}
        return arr
    }

    private suspend fun reconcileNativeState(db: PotholeDatabase) {
        val serviceStatus = DriveForegroundService.status()
        val activeSessionId = serviceStatus.sessionId
            ?.takeIf { serviceStatus.isRunning || serviceStatus.isStopping }
        val now = System.currentTimeMillis() / 1000
        if (activeSessionId == null) db.sessionDao().markAllStaleInterrupted(now)
        else db.sessionDao().markOtherStaleInterrupted(activeSessionId, now)

        val indexed = db.footageDao().getAllSegments()
        indexed.filter { !File(it.filePath).isFile }.forEach { db.footageDao().deleteSegment(it.id) }
        val indexedPaths = indexed.filter { File(it.filePath).isFile }.mapTo(HashSet()) { it.filePath }
        // Stale rows must be removed even when Android has already removed the whole
        // footage directory (for example after storage cleanup outside the app).
        val indexedKeyframes = db.driveKeyframeDao().getAll()
        indexedKeyframes.filter { frame ->
            runCatching {
                val root = FootagePathPolicy.sessionDirectory(context.filesDir, frame.sessionId)
                !FootagePathPolicy.keyframeFile(root, frame.filePath).isFile
            }.getOrDefault(true)
        }.forEach { db.driveKeyframeDao().deleteKeyframe(it.id) }
        val indexedKeyframePaths = indexedKeyframes
            .filter { File(it.filePath).isFile }
            .mapTo(HashSet()) { it.filePath }
        val footageRoot = File(context.filesDir, "footage")
        if (!footageRoot.isDirectory) return
        val orphanFiles = footageRoot.walkTopDown()
            .filter { it.isFile && it.extension.equals("mp4", ignoreCase = true) }
            .filter { it.absolutePath !in indexedPaths }
            .filter { it.parentFile?.name != activeSessionId }
            .toList()
        for (file in orphanFiles) {
            if (file.delete()) continue
            val orphanSessionId = file.parentFile?.name ?: "interrupted-${file.lastModified()}"
            if (db.sessionDao().getSession(orphanSessionId) == null) {
                db.sessionDao().insertSession(SessionEntity(
                    id = orphanSessionId,
                    startedAt = orphanSessionId.toLongOrNull()?.div(1000)
                        ?: (file.lastModified() / 1000),
                    endedAt = now,
                    status = "interrupted"
                ))
            }
            db.footageDao().insertSegment(FootageSegmentEntity(
                sessionId = orphanSessionId,
                filePath = file.absolutePath,
                startedAt = file.lastModified() / 1000,
                endedAt = now,
                durationMs = 0,
                bytes = file.length(),
                errorCode = -1000,
                complete = false
            ))
        }
        // A crash can happen after an atomic JPEG rename but before the Room insert.
        // Such files have no GPS/timing identity and cannot be replayed safely. Temporary
        // files are likewise never valid evidence. Avoid the active session while its
        // write transaction may still be in flight.
        footageRoot.walkTopDown()
            .filter(File::isFile)
            .filter { it.parentFile?.name == "keyframes" }
            .filter { it.parentFile?.parentFile?.name != activeSessionId }
            .filter { it.extension.equals("tmp", ignoreCase = true) ||
                (it.extension.equals("jpg", ignoreCase = true) && it.absolutePath !in indexedKeyframePaths) }
            .toList()
            .forEach { runCatching { it.delete() } }
        footageRoot.walkBottomUp()
            .filter { it.isDirectory && it != footageRoot }
            .forEach { directory -> if (directory.listFiles().isNullOrEmpty()) directory.delete() }
    }

    private suspend fun reconcileNativeStateOnce(db: PotholeDatabase) {
        if (nativeStateReconciled) return
        nativeStateReconcileMutex.withLock {
            if (nativeStateReconciled) return@withLock
            reconcileNativeState(db)
            nativeStateReconciled = true
        }
    }

    private fun requireDriveReplayIsIdle(sessionId: String) {
        val status = DriveForegroundService.status()
        if ((status.isRunning || status.isStopping) && status.sessionId == sessionId) {
            throw IllegalStateException("Stop this drive before analysing its saved frames")
        }
    }

    private fun parseGpsTrack(json: String): JSArray {
        val arr = JSArray()
        try {
            val parsed = JSONArray(json)
            for (i in 0 until parsed.length()) {
                arr.put(parsed.getJSONArray(i))
            }
        } catch (_: Exception) {}
        return arr
    }

    private fun hasDrivePermissions(): Boolean =
        ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED &&
            (ContextCompat.checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED ||
                ContextCompat.checkSelfPermission(context, Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED)

    private fun hasNotificationPermission(): Boolean =
        NotificationHelper.canShowDriveNotification(context)

    private fun statusObject(status: dev.aiengg.potholereporter.drive.DriveStatusSnapshot) = JSObject().apply {
        put("isRunning", status.isRunning)
        put("isPaused", status.isPaused)
        put("isPausing", status.isPausing)
        put("isStopping", status.isStopping)
        put("sessionId", status.sessionId)
        put("checked", status.checked)
        put("found", status.found)
        put("already", status.already)
        put("queued", status.queued)
        put("dropped", status.dropped)
        put("status", status.status)
        put("recordingEnabled", status.recordingEnabled)
        put("isRecording", status.isRecording)
        put("videoSupported", status.videoSupported)
        put("segmentCount", status.segmentCount)
        put("recordedBytes", status.recordedBytes)
        put("cameraActive", status.cameraActive)
        put("recordingIssue", status.recordingIssue)
        put("keyframeCount", status.keyframeCount)
        put("remainingMs", status.remainingMs)
        put("maxDurationMinutes", status.maxDurationMinutes)
    }

    private suspend fun nearbyVideoFrameDataUrls(
        capturedAtMs: Long,
        sessionId: String,
        db: PotholeDatabase
    ): List<Pair<Long, String>> = withContext(Dispatchers.IO) {
        val contextOffsetMs = 900L
        val targetTimes = listOf(capturedAtMs - contextOffsetMs, capturedAtMs + contextOffsetMs)
        val segments = db.footageDao().getSegmentsNear(
            sessionId,
            (capturedAtMs - 2_000L).coerceAtLeast(0L) / 1_000L,
            (capturedAtMs + 2_999L) / 1_000L
        )
        if (segments.isEmpty()) return@withContext emptyList()
        val sessionRoot = try {
            FootagePathPolicy.sessionDirectory(context.filesDir, sessionId)
        } catch (_: Exception) {
            return@withContext emptyList()
        }

        fun distanceFromSegment(targetMs: Long, segment: FootageSegmentEntity): Long {
            val startMs = segment.startedAt * 1_000L
            val durationEndMs = startMs + segment.durationMs.coerceAtLeast(0L)
            val endMs = maxOf(durationEndMs, segment.endedAt * 1_000L)
            return when {
                targetMs < startMs -> startMs - targetMs
                targetMs > endMs -> targetMs - endMs
                else -> 0L
            }
        }

        val selected = targetTimes.mapNotNull { targetMs ->
            val segment = segments.minByOrNull { distanceFromSegment(targetMs, it) }
                ?: return@mapNotNull null
            if (distanceFromSegment(targetMs, segment) > 1_500L) null else segment to targetMs
        }
        val results = mutableListOf<Pair<Long, String>>()
        selected.groupBy({ it.first }, { it.second }).forEach { (segment, targets) ->
            val video = try {
                FootagePathPolicy.segmentFile(sessionRoot, segment.filePath)
            } catch (_: Exception) {
                return@forEach
            }
            if (!video.isFile) return@forEach
            val retriever = MediaMetadataRetriever()
            try {
                retriever.setDataSource(video.absolutePath)
                targets.sorted().forEach targetLoop@{ targetMs ->
                    var bitmap: Bitmap? = null
                    var scaled: Bitmap? = null
                    try {
                        val offsetMs = (targetMs - segment.startedAt * 1_000L)
                            .coerceIn(0L, segment.durationMs.coerceAtLeast(0L))
                        bitmap = retriever.getFrameAtTime(
                            offsetMs * 1_000L,
                            MediaMetadataRetriever.OPTION_CLOSEST
                        ) ?: return@targetLoop
                        val source = bitmap ?: return@targetLoop
                        val scale = minOf(1f, 640f / maxOf(source.width, source.height).toFloat())
                        val width = maxOf(1, (source.width * scale).toInt())
                        val height = maxOf(1, (source.height * scale).toInt())
                        scaled = Bitmap.createScaledBitmap(source, width, height, true)
                        val bytes = ByteArrayOutputStream().use { stream ->
                            if (!(scaled ?: source).compress(Bitmap.CompressFormat.JPEG, 72, stream)) {
                                return@targetLoop
                            }
                            stream.toByteArray()
                        }
                        results += targetMs to (
                            "data:image/jpeg;base64," + Base64.encodeToString(bytes, Base64.NO_WRAP)
                        )
                    } catch (_: Exception) {
                        // Keep the evidence keyframe usable when either temporal sample
                        // is unavailable or a device decoder rejects this clip.
                    } finally {
                        if (scaled != null && scaled !== bitmap && scaled?.isRecycled == false) scaled?.recycle()
                        if (bitmap?.isRecycled == false) bitmap?.recycle()
                    }
                }
            } catch (_: Exception) {
                // A finalized keyframe is still valid single-view evidence.
            } finally {
                runCatching { retriever.release() }
            }
        }
        results.sortedBy { it.first }
    }

    private fun endSummaryObject(summary: dev.aiengg.potholereporter.drive.DriveEndSummary) = JSObject().apply {
        put("stopped", true)
        put("sessionId", summary.sessionId)
        put("checked", summary.checked)
        put("found", summary.found)
        put("already", summary.already)
        put("error", summary.error)
        put("discarded", summary.discarded)
        put("reason", summary.reason)
    }

    private fun fileAsDataUrl(path: String?): String? {
        if (path.isNullOrBlank()) return null
        val file = File(path)
        if (!file.isFile || file.length() > 8L * 1024 * 1024) return null
        return "data:image/jpeg;base64," + Base64.encodeToString(file.readBytes(), Base64.NO_WRAP)
    }

    private fun nullableFiniteFloat(obj: JSONObject, key: String): Float? {
        if (!obj.has(key) || obj.isNull(key)) return null
        val value = obj.optDouble(key, Double.NaN)
        if (!value.isFinite() || value > Float.MAX_VALUE || value < -Float.MAX_VALUE) {
            throw IllegalArgumentException("repair target $key is invalid")
        }
        return value.toFloat()
    }

    private fun decodeImageDataUrl(value: String): Pair<String, ByteArray> {
        if (value.length > MAX_REPAIR_TARGET_IMAGE_BYTES * 2) {
            throw IllegalArgumentException("repair target photo is too large")
        }
        val comma = value.indexOf(',')
        if (comma <= 5) throw IllegalArgumentException("repair target photo is invalid")
        val header = value.substring(5, comma).lowercase()
        val parts = header.split(';')
        if (parts.size != 2 || parts[1] != "base64") {
            throw IllegalArgumentException("repair target photo is invalid")
        }
        val mime = when (parts[0]) {
            "image/jpeg", "image/jpg" -> "image/jpeg"
            "image/png" -> "image/png"
            "image/webp" -> "image/webp"
            "image/gif" -> "image/gif"
            else -> throw IllegalArgumentException("repair target photo type is unsupported")
        }
        val bytes = try {
            Base64.decode(value.substring(comma + 1), Base64.DEFAULT)
        } catch (_: IllegalArgumentException) {
            throw IllegalArgumentException("repair target photo is invalid")
        }
        if (bytes.isEmpty() || bytes.size > MAX_REPAIR_TARGET_IMAGE_BYTES) {
            throw IllegalArgumentException("repair target photo is empty or too large")
        }
        return mime to bytes
    }

    override fun handleOnDestroy() {
        pluginScope.cancel()
        DriveForegroundService.onStatusListener = null
        DriveForegroundService.onReportListener = null
        DriveForegroundService.onDriveEndedListener = null
        super.handleOnDestroy()
    }
}
