package com.gauravsen.potholereporter.plugin

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.util.Base64
import androidx.core.content.ContextCompat
import androidx.core.content.FileProvider
import com.gauravsen.potholereporter.MainActivity
import com.gauravsen.potholereporter.db.FootageSegmentEntity
import com.gauravsen.potholereporter.db.PotholeDatabase
import com.gauravsen.potholereporter.db.SessionEntity
import com.gauravsen.potholereporter.drive.DriveEndSummary
import com.gauravsen.potholereporter.drive.DriveForegroundService
import com.gauravsen.potholereporter.drive.NotificationHelper
import com.getcapacitor.JSArray
import com.getcapacitor.JSObject
import com.getcapacitor.Plugin
import com.getcapacitor.PluginCall
import com.getcapacitor.PluginMethod
import com.getcapacitor.annotation.CapacitorPlugin
import com.getcapacitor.annotation.Permission
import com.getcapacitor.annotation.PermissionCallback
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import java.io.File
import java.util.UUID

internal object FootagePathPolicy {
    // Drive IDs are directory names generated by the app. Keep them to one portable,
    // unambiguous path component; dots and separators have no valid use here.
    private val safeSessionId = Regex("[A-Za-z0-9][A-Za-z0-9_-]{0,127}")

    fun sessionDirectory(filesDir: File, sessionId: String): File {
        require(safeSessionId.matches(sessionId)) { "Invalid drive session" }
        val footageRoot = File(filesDir, "footage").canonicalFile
        val target = File(footageRoot, sessionId).canonicalFile
        require(target != footageRoot && target.parentFile == footageRoot) {
            "Invalid drive session"
        }
        return target
    }

    fun segmentFile(sessionDirectory: File, storedPath: String): File {
        val canonicalSession = sessionDirectory.canonicalFile
        val target = File(storedPath).canonicalFile
        require(target != canonicalSession && target.parentFile == canonicalSession) {
            "Stored footage path is outside this drive"
        }
        return target
    }
}

internal class PendingStartGate<T> {
    private var settled = false
    private var cancellationRequested = false
    private var startRequestAccepted = false
    private var stopIntentQueued = false
    private val stopWaiters = mutableListOf<T>()

    @Synchronized
    fun requestCancellation(stopWaiter: T? = null): Boolean {
        if (settled) return false
        cancellationRequested = true
        if (stopWaiter != null) stopWaiters.add(stopWaiter)
        return true
    }

    @Synchronized
    fun isCancellationRequested(): Boolean = cancellationRequested

    @Synchronized
    fun hasStopWaiters(): Boolean = stopWaiters.isNotEmpty()

    @Synchronized
    fun anyWaiter(predicate: (T) -> Boolean): Boolean = stopWaiters.any(predicate)

    @Synchronized
    fun claimReady(): Boolean {
        if (settled || cancellationRequested) return false
        settled = true
        return true
    }

    @Synchronized
    fun markStartRequestAccepted(): Boolean {
        startRequestAccepted = true
        return cancellationRequested
    }

    @Synchronized
    fun queueStopIntentOnce(): Boolean {
        if (!startRequestAccepted || stopIntentQueued) return false
        stopIntentQueued = true
        return true
    }

    @Synchronized
    fun settleCancellation(): List<T> {
        if (settled) return emptyList()
        settled = true
        return stopWaiters.toList().also { stopWaiters.clear() }
    }
}

@CapacitorPlugin(
    name = "DriveMode",
    permissions = [
        Permission(strings = [Manifest.permission.CAMERA], alias = "camera"),
        Permission(
            strings = [Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION],
            alias = "location"
        ),
        Permission(strings = [Manifest.permission.POST_NOTIFICATIONS], alias = "notifications")
    ]
)
class DriveModePlugin : Plugin() {

    private val pluginScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val pendingStartLock = Any()
    private var pendingStart: PendingDriveStart? = null

    private data class PendingDriveStart(
        val call: PluginCall,
        val requestId: String = UUID.randomUUID().toString(),
        val gate: PendingStartGate<PendingCancellationWaiter> = PendingStartGate()
    )

    private data class PendingCancellationWaiter(
        val discardData: Boolean,
        val onStopped: (DriveEndSummary?) -> Unit,
        val onFailure: () -> Unit
    )

    private companion object {
        const val START_READY_TIMEOUT_MS = 12_000L
        const val START_CANCEL_TIMEOUT_MS = 25_000L
        const val START_POLL_MS = 50L
    }

    override fun load() {
        super.load()
        DriveForegroundService.onStatusListener = { status ->
            val data = JSObject().apply {
                put("isRunning", status.isRunning)
                put("isPaused", status.isPaused)
                put("isPausing", status.isPausing)
                put("isStopping", status.isStopping)
                put("sessionId", status.sessionId)
                put("checked", status.checked)
                put("found", status.found)
                put("already", status.already)
                put("queued", status.queued)
                put("dropped", status.dropped)
                put("status", status.status)
                put("recordingEnabled", status.recordingEnabled)
                put("isRecording", status.isRecording)
                put("videoSupported", status.videoSupported)
                put("segmentCount", status.segmentCount)
                put("recordedBytes", status.recordedBytes)
                put("cameraActive", status.cameraActive)
                put("recordingIssue", status.recordingIssue)
            }
            notifyListeners("driveStatusChange", data)
        }

        DriveForegroundService.onReportListener = { reportId, damageType, address ->
            val data = JSObject().apply {
                put("reportId", reportId)
                put("damageType", damageType)
                put("address", address)
            }
            notifyListeners("reportFound", data)
        }

        DriveForegroundService.onDriveEndedListener = { summary ->
            notifyListeners("driveEnded", endSummaryObject(summary))
        }
    }

    @PluginMethod
    fun startDrive(call: PluginCall) {
        val apiKey = call.getString("apiKey") ?: ""
        val model = call.getString("model") ?: "gpt-5-mini"
        val detail = call.getString("detail") ?: "high"
        val language = call.getString("language") ?: "en"
        val debug = call.getBoolean("debug") ?: false
        val recordVideo = call.getBoolean("recordVideo") ?: false

        if (!hasDrivePermissions()) {
            call.reject("Camera and location permission are required before Drive Mode can start")
            return
        }
        if (!hasNotificationPermission()) {
            call.reject("Enable Pothole Reporter notifications in Android Settings so camera use is always visible")
            return
        }
        if (apiKey.isBlank()) {
            call.reject("An OpenAI API key is required")
            return
        }
        val existing = DriveForegroundService.status()
        if (existing.isRunning) {
            // This call did not create that session. During a phone/video-call camera
            // interruption it is legitimately running with cameraActive=false; return
            // the truthful status without timing out or stopping somebody else's drive.
            call.resolve(statusObject(existing))
            return
        }
        if (existing.isStopping) {
            call.reject("The previous drive is still stopping safely")
            return
        }
        val pending = PendingDriveStart(call)
        val accepted = synchronized(pendingStartLock) {
            if (pendingStart != null) false else {
                pendingStart = pending
                true
            }
        }
        if (!accepted) {
            call.reject("Drive Mode is already starting")
            return
        }
        val context = context
        val serviceIntent = Intent(context, DriveForegroundService::class.java).apply {
            action = DriveForegroundService.ACTION_START
            putExtra(DriveForegroundService.EXTRA_API_KEY, apiKey)
            putExtra(DriveForegroundService.EXTRA_MODEL, model)
            putExtra(DriveForegroundService.EXTRA_DETAIL, detail)
            putExtra(DriveForegroundService.EXTRA_LANGUAGE, language)
            putExtra(DriveForegroundService.EXTRA_DEBUG, debug)
            putExtra(DriveForegroundService.EXTRA_RECORD_VIDEO, recordVideo)
            putExtra(DriveForegroundService.EXTRA_START_REQUEST_ID, pending.requestId)
        }

        try {
            ContextCompat.startForegroundService(context, serviceIntent)
        } catch (error: Exception) {
            synchronized(pendingStartLock) {
                if (pendingStart === pending) pendingStart = null
            }
            val waiters = pending.gate.settleCancellation()
            call.reject("Drive Mode could not start: ${error.message ?: "service start failed"}")
            waiters.forEach { it.onStopped(null) }
            return
        }
        if (pending.gate.markStartRequestAccepted()) queuePendingStartStop(pending)
        monitorPendingStart(pending)
    }

    @PluginMethod
    fun pauseDrive(call: PluginCall) {
        val service = DriveForegroundService.activeService
        if (service == null) call.resolve(statusObject(DriveForegroundService.status()))
        else service.pauseDrive { call.resolve(statusObject(it)) }
    }

    @PluginMethod
    fun resumeDrive(call: PluginCall) {
        val service = DriveForegroundService.activeService
        if (service == null) call.resolve(statusObject(DriveForegroundService.status()))
        else service.resumeDrive { call.resolve(statusObject(it)) }
    }

    @PluginMethod
    fun stopDrive(call: PluginCall) {
        val waiter = PendingCancellationWaiter(
            discardData = false,
            onStopped = { summary ->
                call.resolve(summary?.let(::endSummaryObject) ?: JSObject().apply {
                    put("stopped", true)
                    put("discarded", true)
                    put("cancelledStart", true)
                })
            },
            onFailure = { call.reject("Drive start could not be cancelled safely") }
        )
        val pending = synchronized(pendingStartLock) {
            pendingStart?.takeIf { it.gate.requestCancellation(waiter) }
        }
        if (pending != null) {
            queuePendingStartStop(pending)
            return
        }
        val service = DriveForegroundService.activeService
        if (service != null) {
            service.stopDriveSession { summary -> call.resolve(endSummaryObject(summary)) }
        } else {
            call.resolve(JSObject().apply { put("stopped", false) })
        }
    }

    private fun monitorPendingStart(pending: PendingDriveStart) {
        pluginScope.launch {
            val readyDeadline = System.currentTimeMillis() + START_READY_TIMEOUT_MS
            var failure: String? = null
            while (System.currentTimeMillis() < readyDeadline) {
                if (pending.gate.isCancellationRequested()) {
                    failure = "Drive start was cancelled"
                    break
                }
                val completedStart = DriveForegroundService.completedStartSummary(pending.requestId)
                if (completedStart != null) {
                    pending.gate.requestCancellation()
                    failure = completedStart.error ?: "Drive camera failed to start"
                    break
                }
                val status = DriveForegroundService.status()
                if (status.isStopping) {
                    pending.gate.requestCancellation()
                    failure = status.recordingIssue
                        ?: status.status.takeUnless { it.isBlank() || it == "Stopping safely" }
                        ?: "Drive camera failed to start"
                    break
                }
                // Pause is a valid, user-visible terminal state for startup. It turns
                // the camera off deliberately and must not become a 12-second failure.
                if (DriveForegroundService.activeStartRequestId() == pending.requestId &&
                    status.isRunning && (status.cameraActive || status.isPaused)) {
                    if (pending.gate.claimReady()) {
                        synchronized(pendingStartLock) {
                            if (pendingStart === pending) pendingStart = null
                        }
                        pending.call.resolve(statusObject(status))
                        return@launch
                    }
                    failure = "Drive start was cancelled"
                    break
                }
                delay(START_POLL_MS)
            }

            if (failure == null) {
                pending.gate.requestCancellation()
                failure = "Drive camera did not become ready within ${START_READY_TIMEOUT_MS / 1000} seconds"
            }
            // A user Stop queues ACTION_STOP at request time. Timeout/camera-failure
            // cleanup does not enqueue a fresh FGS start; it stops the active/pending
            // component directly and waits for the service's durable Stop callback.
            if (pending.gate.hasStopWaiters()) queuePendingStartStop(pending)
            val discardData = pending.gate.anyWaiter { it.discardData }
            val cancellation = awaitPendingStartCancellation(pending, discardData)
            val waiters = pending.gate.settleCancellation()
            val finalSummary = cancellation.summary?.let { summary ->
                if (waiters.any { it.discardData }) summary.copy(discarded = true) else summary
            }
            synchronized(pendingStartLock) {
                if (pendingStart === pending) pendingStart = null
            }
            pending.call.reject(failure ?: "Drive camera failed to start")
            waiters.forEach { waiter ->
                if (cancellation.stopped) waiter.onStopped(finalSummary)
                else waiter.onFailure()
            }
        }
    }

    private fun queuePendingStartStop(pending: PendingDriveStart) {
        if (!pending.gate.queueStopIntentOnce()) return
        // This request is queued only after ACTION_START was accepted, while the user
        // is still in the foreground. Android delivers the two starts in order, so a
        // delayed ACTION_START cannot survive as a hidden camera session.
        runCatching {
            context.startService(Intent(context, DriveForegroundService::class.java).apply {
                action = DriveForegroundService.ACTION_STOP
                putExtra(DriveForegroundService.EXTRA_STOP_REQUEST_ID, pending.requestId)
                putExtra(
                    DriveForegroundService.EXTRA_STOP_DISCARD_DATA,
                    pending.gate.anyWaiter { it.discardData }
                )
            })
        }
    }

    private data class PendingCancellationResult(
        val stopped: Boolean,
        val summary: DriveEndSummary?
    )

    private suspend fun awaitPendingStartCancellation(
        pending: PendingDriveStart,
        discardData: Boolean
    ): PendingCancellationResult {
        val completion = CompletableDeferred<DriveEndSummary>()
        var callbackRegistered = false
        var lastStatus = DriveForegroundService.status()
        val deadline = System.currentTimeMillis() + START_CANCEL_TIMEOUT_MS
        while (System.currentTimeMillis() < deadline) {
            DriveForegroundService.completedStartSummary(pending.requestId)?.let {
                return PendingCancellationResult(true, it)
            }
            val service = DriveForegroundService.activeService
            lastStatus = DriveForegroundService.status()
            val activeRequest = DriveForegroundService.activeStartRequestId()
            if (!callbackRegistered && activeRequest == pending.requestId && service != null &&
                (lastStatus.isRunning || lastStatus.isStopping)) {
                callbackRegistered = true
                withContext(Dispatchers.Main) {
                    service.stopDriveSession(
                        reason = "Drive start cancelled",
                        discardData = discardData
                    ) { summary -> completion.complete(summary) }
                }
            }
            if (completion.isCompleted) {
                return PendingCancellationResult(true, completion.await())
            }
            if (callbackRegistered && DriveForegroundService.activeService == null) {
                return PendingCancellationResult(true, cancellationSummary(lastStatus, discardData))
            }
            delay(START_POLL_MS)
        }

        // The service never acknowledged the queued cancellation. Force-stop this
        // component, then verify the in-process service reference is gone before any
        // pending Stop call is allowed to resolve.
        withContext(Dispatchers.Main) {
            if (DriveForegroundService.activeStartRequestId() in arrayOf(null, pending.requestId)) {
                context.stopService(Intent(context, DriveForegroundService::class.java))
            }
        }
        val forceDeadline = System.currentTimeMillis() + 2_000L
        while (System.currentTimeMillis() < forceDeadline &&
            DriveForegroundService.activeService != null) {
            delay(START_POLL_MS)
        }
        return PendingCancellationResult(
            stopped = DriveForegroundService.completedStartSummary(pending.requestId) != null ||
                DriveForegroundService.activeStartRequestId() != pending.requestId,
            summary = completion.takeIf { it.isCompleted }?.await()
                ?: DriveForegroundService.completedStartSummary(pending.requestId)
                ?: cancellationSummary(lastStatus, discardData)
        )
    }

    private fun cancellationSummary(
        status: com.gauravsen.potholereporter.drive.DriveStatusSnapshot,
        discardData: Boolean
    ) =
        DriveEndSummary(
            sessionId = status.sessionId.orEmpty(),
            checked = status.checked,
            found = status.found,
            already = status.already,
            discarded = discardData
        )

    @PluginMethod
    fun getStatus(call: PluginCall) {
        call.resolve(statusObject(DriveForegroundService.status()))
    }

    @PluginMethod
    fun attachPreview(call: PluginCall) {
        val left = call.getDouble("left") ?: 0.0
        val top = call.getDouble("top") ?: 0.0
        val width = call.getDouble("width") ?: 0.0
        val height = call.getDouble("height") ?: 0.0
        val viewportWidth = call.getDouble("viewportWidth") ?: 0.0
        val viewportHeight = call.getDouble("viewportHeight") ?: 0.0
        if (width <= 0 || height <= 0 || viewportWidth <= 0 || viewportHeight <= 0) {
            call.reject("Preview bounds are invalid")
            return
        }
        if (DriveForegroundService.activeService == null || !DriveForegroundService.status().isRunning) {
            call.reject("Drive camera is still starting")
            return
        }
        (activity as? MainActivity)?.showDrivePreview(left, top, width, height, viewportWidth, viewportHeight)
        call.resolve()
    }

    @PluginMethod
    fun detachPreview(call: PluginCall) {
        (activity as? MainActivity)?.hideDrivePreview()
        call.resolve()
    }

    @PluginMethod
    fun setVideoRecording(call: PluginCall) {
        val enabled = call.getBoolean("enabled") ?: false
        val service = DriveForegroundService.activeService
        if (service == null || !DriveForegroundService.status().isRunning) {
            call.reject("Drive Mode is not running")
            return
        }
        service.setVideoRecordingEnabled(enabled) { call.resolve(statusObject(it)) }
    }

    @PluginMethod
    fun requestDrivePermissions(call: PluginCall) {
        val aliases = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            arrayOf("camera", "location", "notifications")
        } else arrayOf("camera", "location")
        requestPermissionForAliases(aliases, call, "drivePermissionsResult")
    }

    @PermissionCallback
    private fun drivePermissionsResult(call: PluginCall) {
        val ret = JSObject().apply {
            put("granted", hasDrivePermissions())
            put("notificationsGranted", Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU ||
                ContextCompat.checkSelfPermission(context, Manifest.permission.POST_NOTIFICATIONS) == PackageManager.PERMISSION_GRANTED)
        }
        call.resolve(ret)
    }

    @PluginMethod
    fun syncReports(call: PluginCall) {
        pluginScope.launch {
            try {
                val db = PotholeDatabase.getDatabase(context)
                val unsynced = db.reportDao().getUnsyncedReports()
                val array = JSArray()
                for (r in unsynced) {
                    val obj = JSObject().apply {
                        put("id", r.id)
                        put("created_at", r.createdAt)
                        put("lat", r.lat)
                        put("lng", r.lng)
                        put("address", r.address)
                        put("photo_data_url", r.photoDataUrl)
                        put("photo_path", r.photoPath)
                        put("photo_full_data_url", fileAsDataUrl(r.photoFullPath ?: r.photoPath))
                        put("is_reportable", r.isReportable)
                        put("is_pothole", r.isPothole)
                        put("damage_type", r.damageType)
                        put("assessment", r.assessment)
                        put("image_quality", r.imageQuality)
                        put("on_drivable_surface", r.onDrivableSurface)
                        put("has_broken_edge_or_rim", r.hasBrokenEdgeOrRim)
                        put("has_depth_or_surface_loss", r.hasDepthOrSurfaceLoss)
                        put("temporal_consistency", r.temporalConsistency)
                        put("size", r.size)
                        put("decision", r.decision)
                        put("description", r.description)
                        put("email_subject", r.emailSubject)
                        put("email_body", r.emailBody)
                        put("status", r.status)
                        put("detection_model", r.detectionModel)
                        put("image_detail", r.imageDetail)
                        put("prompt_version", r.promptVersion)
                        put("schema_version", r.schemaVersion)
                        put("evidence_count", r.evidenceCount)
                        put("drive_id", r.driveId)
                        put("capture_source", r.captureSource)
                        put("source_event_key", r.sourceEventKey)
                        put("captured_at", r.capturedAt)
                        put("source_offset_s", r.sourceOffsetS)
                        put("gps_accuracy", r.gpsAccuracy)
                        put("speed_mps", r.speedMps)
                        put("heading", r.heading)
                        put("seen_count", r.seenCount)
                        put("last_seen_at", r.lastSeenAt)
                        put("primary_frame_index", r.primaryFrameIndex)
                        put("debug_capture", r.debugCapture)
                    }
                    array.put(obj)
                }

                val ret = JSObject().apply {
                    put("reports", array)
                    put("count", array.length())
                }
                call.resolve(ret)
            } catch (e: Exception) {
                call.reject("Failed to sync reports: ${e.message}")
            }
        }
    }

    @PluginMethod
    fun acknowledgeReports(call: PluginCall) {
        val idsArray = call.getArray("ids") ?: JSArray()
        val ids = mutableListOf<Long>()
        for (index in 0 until idsArray.length()) {
            val value = idsArray.optLong(index, -1L)
            if (value > 0) ids.add(value)
        }
        pluginScope.launch {
            try {
                if (ids.isNotEmpty()) PotholeDatabase.getDatabase(context).reportDao().markReportsSynced(ids)
                call.resolve(JSObject().apply { put("acknowledged", ids.size) })
            } catch (error: Exception) {
                call.reject("Failed to acknowledge reports: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun openMaps(call: PluginCall) {
        val navigation = Intent(Intent.ACTION_VIEW, Uri.parse("geo:0,0?q="))
        navigation.setPackage("com.google.android.apps.maps")
        val chosen = if (navigation.resolveActivity(context.packageManager) != null) navigation
            else Intent(Intent.ACTION_VIEW, Uri.parse("geo:0,0?q="))
        chosen.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chosen)
        call.resolve()
    }

    @PluginMethod
    fun clearNativeData(call: PluginCall) {
        val clearData = {
          pluginScope.launch {
            try {
                val db = PotholeDatabase.getDatabase(context)
                val reportsRoot = File(context.filesDir, "reports")
                val footageRoot = File(context.filesDir, "footage")
                if (reportsRoot.exists() && (!reportsRoot.deleteRecursively() || reportsRoot.exists())) {
                    throw IllegalStateException("some report photos could not be deleted")
                }
                if (footageRoot.exists() && (!footageRoot.deleteRecursively() || footageRoot.exists())) {
                    throw IllegalStateException("some recorded footage could not be deleted")
                }
                db.footageDao().clearAll()
                db.eventSightingDao().clearAll()
                db.reportDao().clearAll()
                db.sessionDao().clearAll()
                call.resolve()
            } catch (error: Exception) {
                call.reject("Failed to clear native data: ${error.message}")
              }
          }
        }
        val pendingWaiter = PendingCancellationWaiter(
            discardData = true,
            onStopped = { clearData(); Unit },
            onFailure = { call.reject("Failed to clear native data: Drive start could not be cancelled safely") }
        )
        val pending = synchronized(pendingStartLock) {
            pendingStart?.takeIf { it.gate.requestCancellation(pendingWaiter) }
        }
        if (pending != null) {
            queuePendingStartStop(pending)
            return
        }
        val service = DriveForegroundService.activeService
        if (service == null) clearData()
        else service.stopDriveSession("Data cleared", discardData = true) { clearData() }
    }

    @PluginMethod
    fun getDrives(call: PluginCall) {
        pluginScope.launch {
            try {
                val db = PotholeDatabase.getDatabase(context)
                reconcileNativeState(db)
                val sessions = db.sessionDao().getAllSessions()
                val footageBySession = db.footageDao().getAllSegments().groupBy { it.sessionId }
                val array = JSArray()
                for (s in sessions) {
                    val footage = footageBySession[s.id].orEmpty()
                    val obj = JSObject().apply {
                        put("id", s.id)
                        put("started_at", s.startedAt)
                        put("ended_at", s.endedAt)
                        put("checked", s.checkedCount)
                        put("found", s.foundCount)
                        put("already", s.alreadyCount)
                        put("already_ids", parseJsonArray(s.alreadyIdsJson))
                        put("gps_track", parseGpsTrack(s.gpsTrackJson))
                        put("status", s.status)
                        put("footage_segments", footage.size)
                        put("footage_bytes", footage.sumOf { it.bytes })
                        put("footage_duration_ms", footage.sumOf { it.durationMs })
                    }
                    array.put(obj)
                }
                call.resolve(JSObject().apply { put("drives", array) })
            } catch (e: Exception) {
                call.reject("Failed to get drives: ${e.message}")
            }
        }
    }

    @PluginMethod
    fun listFootage(call: PluginCall) {
        val requestedSession = call.getString("sessionId")
        pluginScope.launch {
            try {
                val dao = PotholeDatabase.getDatabase(context).footageDao()
                val segments = if (requestedSession.isNullOrBlank()) dao.getAllSegments()
                    else dao.getSegmentsForSession(requestedSession)
                val array = JSArray()
                segments.forEach { segment ->
                    array.put(JSObject().apply {
                        put("id", segment.id)
                        put("sessionId", segment.sessionId)
                        put("startedAt", segment.startedAt)
                        put("endedAt", segment.endedAt)
                        put("durationMs", segment.durationMs)
                        put("bytes", segment.bytes)
                        put("complete", segment.complete)
                        put("errorCode", segment.errorCode)
                    })
                }
                call.resolve(JSObject().apply { put("segments", array) })
            } catch (error: Exception) {
                call.reject("Failed to list footage: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun shareFootage(call: PluginCall) {
        val requestedSession = call.getString("sessionId")
        if (requestedSession.isNullOrBlank()) {
            call.reject("A drive session is required")
            return
        }
        pluginScope.launch {
            try {
                val segments = PotholeDatabase.getDatabase(context).footageDao()
                    .getSegmentsForSession(requestedSession)
                    .map { File(it.filePath) }
                    .filter(File::isFile)
                if (segments.isEmpty()) {
                    call.reject("No saved video exists for this drive")
                    return@launch
                }
                val uris = ArrayList(segments.map { file ->
                    FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
                })
                val share = Intent(Intent.ACTION_SEND_MULTIPLE).apply {
                    type = "video/mp4"
                    putParcelableArrayListExtra(Intent.EXTRA_STREAM, uris)
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                }
                activity.runOnUiThread {
                    activity.startActivity(Intent.createChooser(share, "Share drive footage"))
                    call.resolve(JSObject().apply { put("shared", uris.size) })
                }
            } catch (error: Exception) {
                call.reject("Failed to share footage: ${error.message}")
            }
        }
    }

    @PluginMethod
    fun deleteFootage(call: PluginCall) {
        val requestedSession = call.getString("sessionId")
        if (requestedSession.isNullOrBlank()) {
            call.reject("A drive session is required")
            return
        }
        try {
            // Reject traversal before querying state or scheduling any filesystem work.
            FootagePathPolicy.sessionDirectory(context.filesDir, requestedSession)
        } catch (_: Exception) {
            call.reject("Invalid drive session")
            return
        }
        val status = DriveForegroundService.status()
        if ((status.isRunning || status.isStopping) && status.sessionId == requestedSession) {
            call.reject("Stop this drive before deleting its footage")
            return
        }
        pluginScope.launch {
            try {
                val dao = PotholeDatabase.getDatabase(context).footageDao()
                val segments = dao.getSegmentsForSession(requestedSession)
                // Resolve and validate every target first. A corrupt database row must
                // not cause a partial deletion before an out-of-scope path is noticed.
                val sessionRoot = FootagePathPolicy.sessionDirectory(context.filesDir, requestedSession)
                val segmentFiles = segments.map {
                    FootagePathPolicy.segmentFile(sessionRoot, it.filePath)
                }
                var deleted = 0
                val failed = segmentFiles.filter { file ->
                    if (!file.exists()) false else if (file.delete()) { deleted++; false } else true
                }
                if (failed.isNotEmpty()) {
                    throw IllegalStateException("${failed.size} video clip(s) could not be deleted")
                }
                if (sessionRoot.exists() && (!sessionRoot.deleteRecursively() || sessionRoot.exists())) {
                    throw IllegalStateException("the footage folder could not be deleted")
                }
                dao.deleteForSession(requestedSession)
                call.resolve(JSObject().apply { put("deleted", deleted) })
            } catch (error: Exception) {
                call.reject("Failed to delete footage: ${error.message}")
            }
        }
    }

    private fun parseJsonArray(json: String): JSArray {
        val arr = JSArray()
        try {
            val parsed = JSONArray(json)
            for (i in 0 until parsed.length()) {
                arr.put(parsed.get(i))
            }
        } catch (_: Exception) {}
        return arr
    }

    private suspend fun reconcileNativeState(db: PotholeDatabase) {
        val serviceStatus = DriveForegroundService.status()
        val activeSessionId = serviceStatus.sessionId
            ?.takeIf { serviceStatus.isRunning || serviceStatus.isStopping }
        val now = System.currentTimeMillis() / 1000
        if (activeSessionId == null) db.sessionDao().markAllStaleInterrupted(now)
        else db.sessionDao().markOtherStaleInterrupted(activeSessionId, now)

        val indexed = db.footageDao().getAllSegments()
        indexed.filter { !File(it.filePath).isFile }.forEach { db.footageDao().deleteSegment(it.id) }
        val indexedPaths = indexed.filter { File(it.filePath).isFile }.mapTo(HashSet()) { it.filePath }
        val footageRoot = File(context.filesDir, "footage")
        if (!footageRoot.isDirectory) return
        val orphanFiles = footageRoot.walkTopDown()
            .filter { it.isFile && it.extension.equals("mp4", ignoreCase = true) }
            .filter { it.absolutePath !in indexedPaths }
            .filter { it.parentFile?.name != activeSessionId }
            .toList()
        for (file in orphanFiles) {
            if (file.delete()) continue
            val orphanSessionId = file.parentFile?.name ?: "interrupted-${file.lastModified()}"
            if (db.sessionDao().getSession(orphanSessionId) == null) {
                db.sessionDao().insertSession(SessionEntity(
                    id = orphanSessionId,
                    startedAt = orphanSessionId.toLongOrNull()?.div(1000)
                        ?: (file.lastModified() / 1000),
                    endedAt = now,
                    status = "interrupted"
                ))
            }
            db.footageDao().insertSegment(FootageSegmentEntity(
                sessionId = orphanSessionId,
                filePath = file.absolutePath,
                startedAt = file.lastModified() / 1000,
                endedAt = now,
                durationMs = 0,
                bytes = file.length(),
                errorCode = -1000,
                complete = false
            ))
        }
        footageRoot.listFiles()?.filter(File::isDirectory)?.forEach { directory ->
            if (directory.listFiles().isNullOrEmpty()) directory.delete()
        }
    }

    private fun parseGpsTrack(json: String): JSArray {
        val arr = JSArray()
        try {
            val parsed = JSONArray(json)
            for (i in 0 until parsed.length()) {
                arr.put(parsed.getJSONArray(i))
            }
        } catch (_: Exception) {}
        return arr
    }

    private fun hasDrivePermissions(): Boolean =
        ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED &&
            (ContextCompat.checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED ||
                ContextCompat.checkSelfPermission(context, Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED)

    private fun hasNotificationPermission(): Boolean =
        NotificationHelper.canShowDriveNotification(context)

    private fun statusObject(status: com.gauravsen.potholereporter.drive.DriveStatusSnapshot) = JSObject().apply {
        put("isRunning", status.isRunning)
        put("isPaused", status.isPaused)
        put("isPausing", status.isPausing)
        put("isStopping", status.isStopping)
        put("sessionId", status.sessionId)
        put("checked", status.checked)
        put("found", status.found)
        put("already", status.already)
        put("queued", status.queued)
        put("dropped", status.dropped)
        put("status", status.status)
        put("recordingEnabled", status.recordingEnabled)
        put("isRecording", status.isRecording)
        put("videoSupported", status.videoSupported)
        put("segmentCount", status.segmentCount)
        put("recordedBytes", status.recordedBytes)
        put("cameraActive", status.cameraActive)
        put("recordingIssue", status.recordingIssue)
    }

    private fun endSummaryObject(summary: com.gauravsen.potholereporter.drive.DriveEndSummary) = JSObject().apply {
        put("stopped", true)
        put("sessionId", summary.sessionId)
        put("checked", summary.checked)
        put("found", summary.found)
        put("already", summary.already)
        put("error", summary.error)
        put("discarded", summary.discarded)
    }

    private fun fileAsDataUrl(path: String?): String? {
        if (path.isNullOrBlank()) return null
        val file = File(path)
        if (!file.isFile || file.length() > 8L * 1024 * 1024) return null
        return "data:image/jpeg;base64," + Base64.encodeToString(file.readBytes(), Base64.NO_WRAP)
    }

    override fun handleOnDestroy() {
        pluginScope.cancel()
        DriveForegroundService.onStatusListener = null
        DriveForegroundService.onReportListener = null
        DriveForegroundService.onDriveEndedListener = null
        super.handleOnDestroy()
    }
}
